spring:
  application:
    name: demo-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/kset_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: dev
        group: KSET_GROUP
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: dev
        group: KSET_GROUP
  config:
    import: optional:nacos:${spring.application.name}.yaml

server:
  port: 8081

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}

knife4j:
  enable: true
