spring:
  application:
    name: demo-micro-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/kset_demo
    username: postgres
    password: postgres
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
  config:
    import:
      - optional:nacos:kset-common.yaml
      - optional:nacos:${spring.application.name}.yaml

server:
  port: 18082

knife4j:
  enable: true

kset:
  monitor:
    backend: cat
    cat:
      initialize: true
