package com.kset.agent.core;

/** Stable built-in error codes exposed by the agent core. */
public enum AgentErrorCode {
    INVALID_REQUEST,
    ID_GENERATION_FAILED,
    INVALID_SNAPSHOT,
    INVALID_RESUME_INPUT,
    PENDING_ACTION_MISMATCH,
    UNSUPPORTED_SNAPSHOT_VERSION,
    INVALID_CONFIGURATION,
    PROTOCOL_NOT_REGISTERED,
    PROTOCOL_INVALID,
    PROTOCOL_CODEC_FAILED,
    MODEL_CALL_FAILED,
    STRATEGY_EXECUTION_FAILED,
    ACTION_NOT_REGISTERED,
    ACTION_EXECUTION_FAILED,
    TOOL_NOT_FOUND,
    TOOL_CANCELLED,
    TOOL_TIMEOUT,
    TOOL_EXECUTION_FAILED,
    TOOL_BATCH_FAILED,
    TOOL_RESULT_UNKNOWN,
    TOOL_IDEMPOTENCY_CONFLICT,
    TOOL_RESULT_MISSING,
    CHECKPOINT_FAILED,
    LISTENER_FAILED,
    EXTENSION_CONTRACT_VIOLATION,
    INTERNAL_ERROR
}
